/** The keys a player may assign to the switcher, and the ones that open help. */
export const SwitcherKeys = {
    // Keys which are allowed to be assigned to Switcher.
    allowedList: [
        'Enter',
        'Space',
        'NumpadEnter',
        '.',
        'ArrowDown',
        'ArrowLeft',
        'ArrowRight',
        'ArrowUp',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '0',
        'a',
        'b',
        'c',
        'd',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
        'A',
        'B',
        'C',
        'D',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Α',
        'Β',
        'Γ',
        'Δ',
        'Ζ',
        'Η',
        'Θ',
        'Ι',
        'Κ',
        'Λ',
        'Μ',
        'Ξ',
        'Ο',
        'Π',
        'Ρ',
        'Σ',
        'Τ',
        'Υ',
        'Φ',
        'Χ',
        'Ψ',
        'Ω',
        'α',
        'β',
        'γ',
        'δ',
        'ζ',
        'η',
        'θ',
        'ι',
        'κ',
        'λ',
        'μ',
        'ξ',
        'ο',
        'π',
        'ρ',
        'σ',
        'τ',
        'υ',
        'φ',
        'χ',
        'ψ',
        'ω',
    ],
    // Keys which are not allowed but trigger help functions.
    escapeList: ['Escape', 'Tab', 'e', 'E', 'ε', 'Ε', 'n', 'N', 'ν', 'Ν'],
    // Keys not allowed (legacy code).
    forbiddenList: [
        'Escape',
        'Tab',
        'ShiftLeft',
        'LeftShift',
        'ShiftRight',
        'RightShift',
        'ControlLeft',
        'LeftControl',
        'ControlRight',
        'RightControl',
        'AltLeft',
        'LeftAlt',
        'AltRight',
        'RightAlt',
        'F1',
        'F2',
        'F3',
        'F4',
        'F5',
        'F6',
        'F7',
        'F8',
        'F9',
        'F10',
        'F11',
        'F12',
        'Backspace',
    ],
};

/**
 * The key an event carries, in the form the settings store it.
 *
 * A named key comes from the event code, because the numeric keypad repeats
 * another key's value. The space bar reads as " " and is stored as "Space".
 */
export function storedKey(event) {
    if (!event.key.length) {
        return null;
    }
    const charCode = event.key.charCodeAt(0);
    if (event.key.length > 1 && charCode < 128) {
        return event.code;
    }
    if (charCode === 32) {
        return 'Space';
    }

    return event.key;
}
